# Site settings
lang: "en-US"
title: "Nathan Jessen"
email: nathan.jessen@gmail.com
description: Portfolio of Nathan Jessen
baseurl: ""
url: "https://nathanjessen.github.io"
categories_path: categories.html
tags_path: tags.html
rss_path: atom.xml

header_pages:
  - _pages/projects.html
  - _pages/posts.html

# Build settings
ignore_theme_config: true
remote_theme: nathanjessen/blogtheme@main

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Dockerfile
  - docker-compose.yml
  - docker-entrypoint.sh
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
  - vendor

permalink: ":categories/:title/"
timezone: "America/Denver"

collections:
  posts:
    output: true
  pages:
    output: true
    permalink: /:name/
  projects:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

kramdown:
  syntax_highlighter: rouge

# Personal Information
author: Nathan Jessen
logo: false

# Social
github_url: https://github.com/nathanjessen
linkedin_url: https://www.linkedin.com/in/njessen/

# jekyll-seo-tag - social profiles
social:
  links:
    - https://github.com/nathanjessen
    - https://www.linkedin.com/in/njessen/

# Customizable Content
recent_posts_title: Recent Posts
recent_posts_content: Thoughts and Insights
featured_title: Portfolio
featured_content: Featured Projects
services_title: Services
services_content: For any project
footer_content: "&copy; 2026 Nathan Jessen"
